/* Generated By:JavaCC: Do not edit this line. LOLCodeParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LOLCodeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int SUBTRACT = 8;
  /** RegularExpression Id. */
  int MULTIPLY = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int MODULO = 11;
  /** RegularExpression Id. */
  int BIGGR = 12;
  /** RegularExpression Id. */
  int SMALLR = 13;
  /** RegularExpression Id. */
  int XOR = 14;
  /** RegularExpression Id. */
  int LOGICAL_AND = 15;
  /** RegularExpression Id. */
  int LOGICAL_OR = 16;
  /** RegularExpression Id. */
  int INCREMENT = 17;
  /** RegularExpression Id. */
  int DECREMENT = 18;
  /** RegularExpression Id. */
  int ASSIGNMENT = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int LOGICAL_NOT = 21;
  /** RegularExpression Id. */
  int NOT_EQUAL = 22;
  /** RegularExpression Id. */
  int ALL = 23;
  /** RegularExpression Id. */
  int ANY = 24;
  /** RegularExpression Id. */
  int MAEK = 25;
  /** RegularExpression Id. */
  int SMOOSH = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int OPEN_PARENS = 28;
  /** RegularExpression Id. */
  int CLOSE_PARENS = 29;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 30;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 31;
  /** RegularExpression Id. */
  int OPEN_BRACE = 32;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 33;
  /** RegularExpression Id. */
  int SEMICOLON = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;
  /** RegularExpression Id. */
  int DBL_QUOTE = 36;
  /** RegularExpression Id. */
  int UNDERSCORE = 37;
  /** RegularExpression Id. */
  int A = 38;
  /** RegularExpression Id. */
  int AN = 39;
  /** RegularExpression Id. */
  int BUKKIT = 40;
  /** RegularExpression Id. */
  int FAIL = 41;
  /** RegularExpression Id. */
  int FOUND = 42;
  /** RegularExpression Id. */
  int GIMMEH = 43;
  /** RegularExpression Id. */
  int GTFO = 44;
  /** RegularExpression Id. */
  int HAI = 45;
  /** RegularExpression Id. */
  int I_HAS_A = 46;
  /** RegularExpression Id. */
  int HOW_DUZ_I = 47;
  /** RegularExpression Id. */
  int IF_U_SAY_SO = 48;
  /** RegularExpression Id. */
  int IM_IN_YR = 49;
  /** RegularExpression Id. */
  int IM_OUTTA_YR = 50;
  /** RegularExpression Id. */
  int IT = 51;
  /** RegularExpression Id. */
  int ITZ = 52;
  /** RegularExpression Id. */
  int IS = 53;
  /** RegularExpression Id. */
  int KTHXBYE = 54;
  /** RegularExpression Id. */
  int MEBBE = 55;
  /** RegularExpression Id. */
  int MKAY = 56;
  /** RegularExpression Id. */
  int NO = 57;
  /** RegularExpression Id. */
  int NOOB = 58;
  /** RegularExpression Id. */
  int NOW = 59;
  /** RegularExpression Id. */
  int NUMBAR = 60;
  /** RegularExpression Id. */
  int NUMBR = 61;
  /** RegularExpression Id. */
  int O = 62;
  /** RegularExpression Id. */
  int OF = 63;
  /** RegularExpression Id. */
  int OIC = 64;
  /** RegularExpression Id. */
  int OMG = 65;
  /** RegularExpression Id. */
  int OMGWTF = 66;
  /** RegularExpression Id. */
  int RLY = 67;
  /** RegularExpression Id. */
  int RLYQ = 68;
  /** RegularExpression Id. */
  int THAN = 69;
  /** RegularExpression Id. */
  int TIL = 70;
  /** RegularExpression Id. */
  int TROOF = 71;
  /** RegularExpression Id. */
  int VISIBLE = 72;
  /** RegularExpression Id. */
  int WAI = 73;
  /** RegularExpression Id. */
  int WILE = 74;
  /** RegularExpression Id. */
  int WIN = 75;
  /** RegularExpression Id. */
  int WTF = 76;
  /** RegularExpression Id. */
  int YA = 77;
  /** RegularExpression Id. */
  int YARN = 78;
  /** RegularExpression Id. */
  int YR = 79;
  /** RegularExpression Id. */
  int IDENTIFIER = 80;
  /** RegularExpression Id. */
  int STRING = 81;
  /** RegularExpression Id. */
  int CHARACTER = 82;
  /** RegularExpression Id. */
  int REAL_NUMBER = 83;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER = 84;
  /** RegularExpression Id. */
  int DIGIT = 85;
  /** RegularExpression Id. */
  int LETTER = 86;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"OBTW\"",
    "\"TLDR\"",
    "<token of kind 6>",
    "\"SUM\"",
    "\"DIFF\"",
    "\"PRODUKT\"",
    "\"QUOSHUNT\"",
    "\"MOD\"",
    "\"BIGGR\"",
    "\"SMALLR\"",
    "\"WON\"",
    "\"BOTH\"",
    "\"EITHER\"",
    "\"UPPIN\"",
    "\"NERFIN\"",
    "\"R\"",
    "\"SAEM\"",
    "\"NOT\"",
    "\"DIFFRINT\"",
    "\"ALL\"",
    "\"ANY\"",
    "\"MAEK\"",
    "\"SMOOSH\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"_\"",
    "\"A\"",
    "\"AN\"",
    "\"BUKKIT\"",
    "\"FAIL\"",
    "\"FOUND\"",
    "\"GIMMEH\"",
    "\"GTFO\"",
    "\"HAI\"",
    "\"I HAS A\"",
    "\"HOW DUZ I\"",
    "\"IF U SAY SO\"",
    "\"IM IN YR\"",
    "\"IM OUTTA YR\"",
    "\"IT\"",
    "\"ITZ\"",
    "\"IS\"",
    "\"KTHXBYE\"",
    "\"MEBBE\"",
    "\"MKAY\"",
    "\"NO\"",
    "\"NOOB\"",
    "\"NOW\"",
    "\"NUMBAR\"",
    "\"NUMBR\"",
    "\"O\"",
    "\"OF\"",
    "\"OIC\"",
    "\"OMG\"",
    "\"OMGWTF\"",
    "\"RLY\"",
    "\"RLY?\"",
    "\"THAN\"",
    "\"TIL\"",
    "\"TROOF\"",
    "\"VISIBLE\"",
    "\"WAI\"",
    "\"WILE\"",
    "\"WIN\"",
    "\"WTF?\"",
    "\"YA\"",
    "\"YARN\"",
    "\"YR\"",
    "<IDENTIFIER>",
    "<STRING>",
    "<CHARACTER>",
    "<REAL_NUMBER>",
    "<DECIMAL_INTEGER>",
    "<DIGIT>",
    "<LETTER>",
  };

}
