HAI FIBONACCI_RECURSIVE
  HOW DUZ I FIBONACCI YR N
    BOTH SAEM 2 AN BIGGR OF 2 AN N, O RLY?
      YA RLY
        FOUND YR 1
      NO WAI
        FOUND YR SUM OF I CAN HAS FIBONACCI DIFF OF N AN 1 AN I CAN HAS FIBONACCI DIFF OF N AN 2
    OIC
  IF U SAY SO
  
  I HAS A N ITZ 0
  IM IN YR LOOP UPPIN YR N WILE N SMALLR THAN 16
    VISIBLE SMOOSH I CAN HAS FIBONACCI N AN ", " MKAY
  IM OUTTA YR LOOP
  VISIBLE "..."
KTHXBYE
