BTW Example taken from http://progopedia.com/language/lolcode/

HAI FIBONACCI
  I HAS A I ITZ 0
  I HAS A FIB1 ITZ 0
  I HAS A FIB2 ITZ 1
  GIMMEH FIBCOUNT
  IM IN YR LOOP UPPIN YR I TIL BOTH SAEM I AN FIBCOUNT
    VISIBLE SMOOSH FIB2 ", " MKAY
    I HAS A FIB3 ITZ SUM OF FIB1 AN FIB2
    FIB1 R FIB2
    FIB2 R FIB3
  IM OUTTA YR LOOP
  VISIBLE "..."
KTHXBYE
