HAI MINITEST

HOW DUZ I ADD YR X AN YR Y
  I HAS A ADDITION ITZ SUM OF X AN Y
  FOUND YR ADDITION
IF U SAY SO

I HAS A X ITZ 5
I HAS A Y ITZ 12
I HAS A Z ITZ I CAN HAS ADD X Y

I CAN HAS ADD Y Z

KTHXBYE